add oracle client in Dockerfile

diff --git a/docker/datahub-actions/Dockerfile b/docker/datahub-actions/Dockerfile
--- a/docker/datahub-actions/Dockerfile
+++ b/docker/datahub-actions/Dockerfile
@@ -42,11 +42,11 @@ RUN apt-get update \
     && python -m pip install --upgrade pip wheel setuptools==57.5.0
 
 RUN if [ $(arch) = "x86_64" ]; then \
-        wget -c https://download.oracle.com/otn_software/linux/instantclient/215000/oracle-instantclient-basic-21.5.0.0.0-1.el8.x86_64.rpm && \
+        wget -c https://download.oracle.com/otn_software/linux/instantclient/215000/oracle-instantclient-basic-21.5.0.0.0-1.el8.x86_64.rpm; \
         alien -i oracle-instantclient-basic-21.5.0.0.0-1.el8.x86_64.rpm; \
     else \
-        echo >&2 "Oracle client cannot be installed for $(arch)" ; exit 1; \
-    fi \
+        echo >&2 "Oracle client cannot be installed for $(arch)"; \
+    fi;
 
 FROM base as prod-install
 COPY datahub-actions /actions-src
